### ISSUE TITLE
framerate does not work

### ISSUE THREAD

**Issue by rgrandpierre** [MattsProjects/pylon_gstreamer#13]
Hi,
I use your program "demopylongstreamer" on a nvidia jetson TX2 (arm64) with a camera Basler acA1440-73gc. I use pylon version 5.2.0.13457. The Basler acA1440-73gc is connected to the Ethernet port of the TX2.
I use the following pipe line:
./demopylongstreamer -window -framerate 5
My problem is that the camera sends a lot more of the 5FPS ask with the pipeline "demopylongstreamer -window -framerate 5", I make the same test with viewer provided with pylon and I get 5fps well.
Do you know where the problem comes from?

Many thanks in advance,
Best regard,
Raphael

**Comment by BaslerSupportUSA** [comment]
Sorry for that! Thanks for finding it! :)

**Comment by MattsProjects** [comment]
FYI, fixed in the latest commit.

**Comment by rgrandpierre** [comment]
Thanks it works! but I have another problem when I try to save the video in a file, the pipe line it stops all alone do you know where it comes from? (i also try as root and i got the same result)

Thank,
Best regard,
Raphael
![image](https://user-images.githubusercontent.com/40458543/69166212-2c9c6880-0af3-11ea-8f0a-ed8b65acba81.png)
