### ISSUE TITLE
Rainbow screen

### ISSUE THREAD

**Issue by NAGARAJUSVS** [MattsProjects/pylon_gstreamer#17]
Hi,

when there is no input to video card , from gstreamer i'm getting rainbow screen instead of black screen.
do we have any setting or parameters to pipeline to get black screen when ther is no input to the video card.

regards,
Nagaraju.

**Comment by MattsProjects** [comment]
Hi Nagaraju,
I'm afraid I don't understand. Can you post a screenshot, as well as tell me which sample you are using from the project? Thanks!
-matt

**Comment by NAGARAJUSVS** [comment]
Hi Mathew,

thanks for the reply,

Please find the below details.
video card: magewell
gsreamer version: 1.8.3



issue:
================================================================

when there is no output to video card, used to get black screen.
After upgrading gstreamer version or latest capture card,  im getting
rainbow screen(snashot attached) when ever there is no feed(video) .
To get black screen instead of rainbow screen, please let me know if  we
have any settings or configurations.



Regards,
Nag

**Comment by MattsProjects** [comment]
Hi Nagaraju,
I'm sorry, but I still don't understand...
Are you using my software here with a Basler camera? I have never heard of such a card before.
I'm afraid that is the only intended use case of my project. If you're using other equipment then it is better to post the question to a more general gstreamer forum...
