### ISSUE TITLE
how to forward gstreamer feed with v4l2videosink

### ISSUE THREAD

**Issue by tameralamiri** [MattsProjects/pylon_gstreamer#7]
demopylongstreamer is working well with autovideosink. However, when i try to use v4l2videosink it crashes with internal data flow error.
is there anyway to fix that?
my main goal is to open the basler camera as a webcam from a browser so i need to include v4l2videosink device=/dev/vedio0 to gstreamer command

i already downloaded v4l2loopback-utils and ran sudo modprobe v4l2loopback exclusive_caps=1 with no success

**Comment by tameralamiri** [comment]
this is the full command i'm using:
sudo ./demopylongstreamer  -parse "gst-launch-1.0 fdsrc ! decodebin3 name=dec ! queue ! videoflip method=vertical-flip ! v4l2sink device=/dev/video0" &> debug.log


and here is the logs:

Press CTRL+C at any time to quit.
Initializing camera and driver...
Using Camera             : Basler acA1920-40uc (22642081)
Camera Area Of Interest  : 1920x1200
Camera Speed             : 40.9987 fps
Applying this Pipeline to the CInstantCameraAppsc: gst-launch-1.0 fdsrc ! decodebin3 name=dec ! queue ! videoflip method=vertical-flip ! v4l2sink device=/dev/video0...
Pipeline Made.
Starting Camera image acquistion and Pylon driver Grab Engine...
Starting pipeline...
ERROR from element source22642081: Internal data stream error.
Debugging info: gstbasesrc.c(2950): gst_base_src_loop (): /GstPipeline:pipeline/GstBin:sourcebin22642081/GstAppSrc:source22642081:
streaming stopped, reason not-negotiated (-4)
Stopping pipeline...
Sending EOS event...
Stopping Camera image acquistion and Pylon image grabbing...

Press Enter to exit.

**Comment by MattsProjects** [comment]
Hi Tamer,
Try this pipeline:
sudo ./demopylongstreamer -parse "gst-launch-1.0 ! **deinterlace** ! v4l2sink device=/dev/video0"

I found the hint from the gstreamer mailing lists. Using deinterlace element works for me...
https://lists.freedesktop.org/archives/gstreamer-devel/2013-September/043136.html
